[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[phases.start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"

[cache]
paths = ["/opt/venv"]
